### ISSUE TITLE
docs: Add Facebook and LinkedIn to the footer section

### ISSUE THREAD

**Issue by vinzvinci** [dev-protocol/app#185]
There's a new social of Dev Protocol that we need to add to the footer section: 

**Here's the URL**
LinkedIn: https://www.linkedin.com/showcase/dev-protocol/
Facebook: https://www.facebook.com/DevProtocol.xyz

**Comment by RandikaR21** [comment]
Hi, I would like to work on this issue. Could it be assigned for me?

**Comment by vinzvinci** [comment]
Hi @RandikaR21, I'll assigned this issue to you. Please follow our contributing guidelines. Thank you!

**Comment by vinzvinci** [comment]
Your PR has been **merged**. I'll be closing this issue, thank you for contributing 😃  🎉
