### ISSUE TITLE
npm ERR! Unable to authenticate, need: Basic realm="GitHub Package Registry"

### ISSUE THREAD

**Issue by narita1980** [dev-protocol/app#4]
If you execute the following command,
```
git clone https://github.com/dev-protocol/app.git
$ cd app
$ npm i
```

An error has occurred.
```
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="GitHub Package Registry"
```

Please tell me about this correspondence method.

**Comment by aggre** [comment]
@narita1980 Sorry for late reply.

This repos using packages that included GitHub Packages, so require [GitHub personal tokens](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line).
Can you add GitHub personal tokens to `.npmrc`, like the following way.

```bash
> echo "//npm.pkg.github.com/:_authToken=XXX_GITHUB_TOKEN_XXX >> ~/.npmrc
```

---

I don't understand, why it requires the token to just installing public packages 🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by narita1980** [comment]
@aggre-san,
thank you!
